[project]
name = "happie"
version = "0.1.0"
description = "An MCP server for working with the Albert Heijn API from your agent"
readme = "README.md"
authors = [
    { name = "Willem Meints", email = "1550763+wmeints@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.4.7",
    "httpx>=0.28.1",
    "typer>=0.27.1",
]

[project.scripts]
happie = "happie:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pydoclint==0.9.1",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
    "ty==0.0.75",
]

[tool.ruff.lint]
extend-select = ["C90", "D"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.pydoclint]
style = "numpy"
skip-checking-short-docstrings = true

